---
:global:
  image_tag: 'ci/semantic-release:${{ github.sha }}'
.github/workflows/build_container.yml:
  publish_pre_build_steps:
    - name: Determine semantic-release version
      id: version
      commands:
        - echo "version=$(jq -r '.dependencies."semantic-release" | ltrimstr("^")' package.json)" >> "$GITHUB_OUTPUT"
    - name: Determine channel tag
      id: channel
      commands:
        - echo "tag=$(echo '${{ github.ref_name }}' | sed 's/^main$/latest/')" >> "$GITHUB_OUTPUT"
  publish_tags:
    - 'ghcr.io/voxpupuli/semantic-release:${{ steps.version.outputs.version }}-${{ steps.channel.outputs.tag }}'
    - 'ghcr.io/voxpupuli/semantic-release:latest'
    - 'docker.io/voxpupuli/semantic-release:${{ steps.version.outputs.version }}-${{ steps.channel.outputs.tag }}'
    - 'docker.io/voxpupuli/semantic-release:latest'
  dockerhub_repository: voxpupuli/semantic-release
